/**
 * Seed data for common miniature paint ranges.
 * Each entry has: name, brand, range, colorFamily, hex.
 */
export const SEED_PAINTS = [
  // ──────────────────────────────────────────────
  // Citadel (Games Workshop) — Base
  // ──────────────────────────────────────────────
  { name: 'Abaddon Black', brand: 'Citadel', range: 'Base', colorFamily: 'Black', hex: '#000000' },
  { name: 'Averland Sunset', brand: 'Citadel', range: 'Base', colorFamily: 'Yellow', hex: '#FBB900' },
  { name: 'Bugmans Glow', brand: 'Citadel', range: 'Base', colorFamily: 'Flesh', hex: '#8C5144' },
  { name: 'Caliban Green', brand: 'Citadel', range: 'Base', colorFamily: 'Green', hex: '#005221' },
  { name: 'Castellan Green', brand: 'Citadel', range: 'Base', colorFamily: 'Green', hex: '#384D20' },
  { name: 'Ceramite White', brand: 'Citadel', range: 'Base', colorFamily: 'White', hex: '#FFFFFF' },
  { name: 'Daemonette Hide', brand: 'Citadel', range: 'Base', colorFamily: 'Purple', hex: '#696685' },
  { name: 'Death Guard Green', brand: 'Citadel', range: 'Base', colorFamily: 'Green', hex: '#848A66' },
  { name: 'Dryad Bark', brand: 'Citadel', range: 'Base', colorFamily: 'Brown', hex: '#3B342E' },
  { name: 'Incubi Darkness', brand: 'Citadel', range: 'Base', colorFamily: 'Teal', hex: '#082E32' },
  { name: 'Jokaero Orange', brand: 'Citadel', range: 'Base', colorFamily: 'Orange', hex: '#EE3823' },
  { name: 'Kantor Blue', brand: 'Citadel', range: 'Base', colorFamily: 'Blue', hex: '#08085A' },
  { name: 'Khorne Red', brand: 'Citadel', range: 'Base', colorFamily: 'Red', hex: '#6A0002' },
  { name: 'Leadbelcher', brand: 'Citadel', range: 'Base', colorFamily: 'Metallic', hex: '#393939' },
  { name: 'Macragge Blue', brand: 'Citadel', range: 'Base', colorFamily: 'Blue', hex: '#2D567C' },
  { name: 'Mechanicus Standard Grey', brand: 'Citadel', range: 'Base', colorFamily: 'Grey', hex: '#7C8286' },
  { name: 'Mephiston Red', brand: 'Citadel', range: 'Base', colorFamily: 'Red', hex: '#991115' },
  { name: 'Mournfang Brown', brand: 'Citadel', range: 'Base', colorFamily: 'Brown', hex: '#663300' },
  { name: 'Naggaroth Night', brand: 'Citadel', range: 'Base', colorFamily: 'Purple', hex: '#562F7E' },
  { name: 'Rakarth Flesh', brand: 'Citadel', range: 'Base', colorFamily: 'Flesh', hex: '#B9ADA1' },
  { name: 'Retributor Armour', brand: 'Citadel', range: 'Base', colorFamily: 'Metallic', hex: '#C39E24' },
  { name: 'Rhinox Hide', brand: 'Citadel', range: 'Base', colorFamily: 'Brown', hex: '#390008' },
  { name: 'Screamer Pink', brand: 'Citadel', range: 'Base', colorFamily: 'Pink', hex: '#9C004A' },
  { name: 'Steel Legion Drab', brand: 'Citadel', range: 'Base', colorFamily: 'Brown', hex: '#655138' },
  { name: 'Stegadon Scale Green', brand: 'Citadel', range: 'Base', colorFamily: 'Teal', hex: '#004261' },
  { name: 'The Fang', brand: 'Citadel', range: 'Base', colorFamily: 'Blue', hex: '#4E5067' },
  { name: 'Thousand Sons Blue', brand: 'Citadel', range: 'Base', colorFamily: 'Blue', hex: '#00506F' },
  { name: 'Waaagh! Flesh', brand: 'Citadel', range: 'Base', colorFamily: 'Green', hex: '#384E49' },
  { name: 'XV-88', brand: 'Citadel', range: 'Base', colorFamily: 'Brown', hex: '#793721' },
  { name: 'Zandri Dust', brand: 'Citadel', range: 'Base', colorFamily: 'Bone', hex: '#9E915C' },

  // ──────────────────────────────────────────────
  // Citadel — Layer
  // ──────────────────────────────────────────────
  { name: 'Administratum Grey', brand: 'Citadel', range: 'Layer', colorFamily: 'Grey', hex: '#B5B5B5' },
  { name: 'Ahriman Blue', brand: 'Citadel', range: 'Layer', colorFamily: 'Blue', hex: '#00708A' },
  { name: 'Altdorf Guard Blue', brand: 'Citadel', range: 'Layer', colorFamily: 'Blue', hex: '#29397B' },
  { name: 'Balor Brown', brand: 'Citadel', range: 'Layer', colorFamily: 'Brown', hex: '#9C6B08' },
  { name: 'Baneblade Brown', brand: 'Citadel', range: 'Layer', colorFamily: 'Brown', hex: '#705E48' },
  { name: 'Bestigor Flesh', brand: 'Citadel', range: 'Layer', colorFamily: 'Flesh', hex: '#F7BD7B' },
  { name: 'Cadian Fleshtone', brand: 'Citadel', range: 'Layer', colorFamily: 'Flesh', hex: '#8D736C' },
  { name: 'Caledor Sky', brand: 'Citadel', range: 'Layer', colorFamily: 'Blue', hex: '#31639C' },
  { name: 'Dawnstone', brand: 'Citadel', range: 'Layer', colorFamily: 'Grey', hex: '#999999' },
  { name: 'Death World Forest', brand: 'Citadel', range: 'Layer', colorFamily: 'Green', hex: '#5D6732' },
  { name: 'Doombull Brown', brand: 'Citadel', range: 'Layer', colorFamily: 'Brown', hex: '#630808' },
  { name: 'Elysian Green', brand: 'Citadel', range: 'Layer', colorFamily: 'Green', hex: '#A5A542' },
  { name: 'Emperors Children', brand: 'Citadel', range: 'Layer', colorFamily: 'Pink', hex: '#EF9CB5' },
  { name: 'Eshin Grey', brand: 'Citadel', range: 'Layer', colorFamily: 'Grey', hex: '#484B4E' },
  { name: 'Evil Sunz Scarlet', brand: 'Citadel', range: 'Layer', colorFamily: 'Red', hex: '#C21920' },
  { name: 'Fenrisian Grey', brand: 'Citadel', range: 'Layer', colorFamily: 'Blue', hex: '#CEDEE7' },
  { name: 'Fire Dragon Bright', brand: 'Citadel', range: 'Layer', colorFamily: 'Orange', hex: '#FF8552' },
  { name: 'Flash Gitz Yellow', brand: 'Citadel', range: 'Layer', colorFamily: 'Yellow', hex: '#FFE700' },
  { name: 'Genestealer Purple', brand: 'Citadel', range: 'Layer', colorFamily: 'Purple', hex: '#7C5CA4' },
  { name: 'Gorthor Brown', brand: 'Citadel', range: 'Layer', colorFamily: 'Brown', hex: '#5F463F' },
  { name: 'Hoeth Blue', brand: 'Citadel', range: 'Layer', colorFamily: 'Blue', hex: '#4C78AF' },
  { name: 'Kabalite Green', brand: 'Citadel', range: 'Layer', colorFamily: 'Green', hex: '#069B7D' },
  { name: 'Karak Stone', brand: 'Citadel', range: 'Layer', colorFamily: 'Bone', hex: '#9B8C7B' },
  { name: 'Kislev Flesh', brand: 'Citadel', range: 'Layer', colorFamily: 'Flesh', hex: '#EEC8C7' },
  { name: 'Loren Forest', brand: 'Citadel', range: 'Layer', colorFamily: 'Green', hex: '#434F38' },
  { name: 'Lothern Blue', brand: 'Citadel', range: 'Layer', colorFamily: 'Blue', hex: '#6B9CCE' },
  { name: 'Moot Green', brand: 'Citadel', range: 'Layer', colorFamily: 'Green', hex: '#A5D610' },
  { name: 'Nurgling Green', brand: 'Citadel', range: 'Layer', colorFamily: 'Green', hex: '#849B63' },
  { name: 'Pink Horror', brand: 'Citadel', range: 'Layer', colorFamily: 'Pink', hex: '#96325C' },
  { name: 'Russ Grey', brand: 'Citadel', range: 'Layer', colorFamily: 'Blue', hex: '#55768A' },
  { name: 'Screaming Skull', brand: 'Citadel', range: 'Layer', colorFamily: 'Bone', hex: '#F0F1CE' },
  { name: 'Skarsnik Green', brand: 'Citadel', range: 'Layer', colorFamily: 'Green', hex: '#5E9067' },
  { name: 'Skrag Brown', brand: 'Citadel', range: 'Layer', colorFamily: 'Brown', hex: '#843910' },
  { name: 'Sotek Green', brand: 'Citadel', range: 'Layer', colorFamily: 'Teal', hex: '#006B5A' },
  { name: 'Stormvermin Fur', brand: 'Citadel', range: 'Layer', colorFamily: 'Grey', hex: '#4D4A4A' },
  { name: 'Sybarite Green', brand: 'Citadel', range: 'Layer', colorFamily: 'Green', hex: '#82C59C' },
  { name: 'Tallarn Sand', brand: 'Citadel', range: 'Layer', colorFamily: 'Brown', hex: '#9C8855' },
  { name: 'Teclis Blue', brand: 'Citadel', range: 'Layer', colorFamily: 'Blue', hex: '#8BB9DD' },
  { name: 'Troll Slayer Orange', brand: 'Citadel', range: 'Layer', colorFamily: 'Orange', hex: '#F46C2E' },
  { name: 'Ulthuan Grey', brand: 'Citadel', range: 'Layer', colorFamily: 'Grey', hex: '#C3C6CD' },
  { name: 'Ushabti Bone', brand: 'Citadel', range: 'Layer', colorFamily: 'Bone', hex: '#EFD9A8' },
  { name: 'Warboss Green', brand: 'Citadel', range: 'Layer', colorFamily: 'Green', hex: '#63B521' },
  { name: 'Warpstone Glow', brand: 'Citadel', range: 'Layer', colorFamily: 'Green', hex: '#106B21' },
  { name: 'White Scar', brand: 'Citadel', range: 'Layer', colorFamily: 'White', hex: '#FFFFFF' },
  { name: 'Wild Rider Red', brand: 'Citadel', range: 'Layer', colorFamily: 'Red', hex: '#EB2E28' },
  { name: 'Xereus Purple', brand: 'Citadel', range: 'Layer', colorFamily: 'Purple', hex: '#5A005A' },
  { name: 'Yriel Yellow', brand: 'Citadel', range: 'Layer', colorFamily: 'Yellow', hex: '#FFCE00' },
  { name: 'Zamesi Desert', brand: 'Citadel', range: 'Layer', colorFamily: 'Yellow', hex: '#C68400' },

  // ──────────────────────────────────────────────
  // Citadel — Shade
  // ──────────────────────────────────────────────
  { name: 'Agrax Earthshade', brand: 'Citadel', range: 'Shade', colorFamily: 'Brown', hex: '#393121' },
  { name: 'Athonian Camoshade', brand: 'Citadel', range: 'Shade', colorFamily: 'Green', hex: '#8B8B66' },
  { name: 'Biel-Tan Green', brand: 'Citadel', range: 'Shade', colorFamily: 'Green', hex: '#547757' },
  { name: 'Carroburg Crimson', brand: 'Citadel', range: 'Shade', colorFamily: 'Red', hex: '#630808' },
  { name: 'Casandora Yellow', brand: 'Citadel', range: 'Shade', colorFamily: 'Yellow', hex: '#E89B0C' },
  { name: 'Drakenhof Nightshade', brand: 'Citadel', range: 'Shade', colorFamily: 'Blue', hex: '#273E51' },
  { name: 'Druchii Violet', brand: 'Citadel', range: 'Shade', colorFamily: 'Purple', hex: '#842994' },
  { name: 'Fuegan Orange', brand: 'Citadel', range: 'Shade', colorFamily: 'Orange', hex: '#C65A10' },
  { name: 'Nuln Oil', brand: 'Citadel', range: 'Shade', colorFamily: 'Black', hex: '#000000' },
  { name: 'Reikland Fleshshade', brand: 'Citadel', range: 'Shade', colorFamily: 'Flesh', hex: '#CE8C42' },
  { name: 'Seraphim Sepia', brand: 'Citadel', range: 'Shade', colorFamily: 'Brown', hex: '#843910' },

  // ──────────────────────────────────────────────
  // Citadel — Metallic
  // ──────────────────────────────────────────────
  { name: 'Auric Armour Gold', brand: 'Citadel', range: 'Layer', colorFamily: 'Metallic', hex: '#E7BD42' },
  { name: 'Balthasar Gold', brand: 'Citadel', range: 'Base', colorFamily: 'Metallic', hex: '#6D3108' },
  { name: 'Brass Scorpion', brand: 'Citadel', range: 'Layer', colorFamily: 'Metallic', hex: '#73372D' },
  { name: 'Gehenna\'s Gold', brand: 'Citadel', range: 'Layer', colorFamily: 'Metallic', hex: '#CCCC33' },
  { name: 'Hashut Copper', brand: 'Citadel', range: 'Layer', colorFamily: 'Metallic', hex: '#9C5221' },
  { name: 'Ironbreaker', brand: 'Citadel', range: 'Layer', colorFamily: 'Metallic', hex: '#7B737B' },
  { name: 'Runefang Steel', brand: 'Citadel', range: 'Layer', colorFamily: 'Metallic', hex: '#B5B5BD' },
  { name: 'Runelord Brass', brand: 'Citadel', range: 'Layer', colorFamily: 'Metallic', hex: '#735A21' },
  { name: 'Warplock Bronze', brand: 'Citadel', range: 'Layer', colorFamily: 'Metallic', hex: '#393121' },

  // ──────────────────────────────────────────────
  // Vallejo Game Color
  // ──────────────────────────────────────────────
  { name: 'Dead White (001)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'White', hex: '#FFFFFF' },
  { name: 'White Primer (002)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'White', hex: '#FFFFFF' },
  { name: 'Pale Flesh (003)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Flesh', hex: '#F6BDB3' },
  { name: 'Elf Skintone (004)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Flesh', hex: '#D7A382' },
  { name: 'Moon Yellow (005)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Yellow', hex: '#FFF103' },
  { name: 'Sun Yellow (006)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Yellow', hex: '#FFCF07' },
  { name: 'Gold Yellow (007)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Yellow', hex: '#FDB318' },
  { name: 'Orange Fire (008)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Orange', hex: '#F1652E' },
  { name: 'Hot Orange (009)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Orange', hex: '#E43027' },
  { name: 'Bloody Red (010)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Red', hex: '#BF282E' },
  { name: 'Gory Red (011)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Red', hex: '#810504' },
  { name: 'Scarlett Red (012)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Red', hex: '#AE0A0A' },
  { name: 'Squid Pink (013)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Pink', hex: '#EF9CB5' },
  { name: 'Warlord Purple (014)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Purple', hex: '#7D1A44' },
  { name: 'Hexed Lichen (015)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Purple', hex: '#5A005A' },
  { name: 'Royal Purple (016)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Purple', hex: '#562F7E' },
  { name: 'Dark Green (028)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Green', hex: '#083C2A' },
  { name: 'Sick Green (029)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Green', hex: '#239378' },
  { name: 'Goblin Green (030)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Green', hex: '#23743C' },
  { name: 'Camouflage Green (031)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Green', hex: '#71753A' },
  { name: 'Scorpy Green (032)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Green', hex: '#48B851' },
  { name: 'Livery Green (033)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Green', hex: '#A9D171' },
  { name: 'Bonewhite (034)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Bone', hex: '#EFD9A8' },
  { name: 'Dead Flesh (035)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Green', hex: '#BCB686' },
  { name: 'Bronze Flesh (036)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Flesh', hex: '#DB945C' },
  { name: 'Filthy Brown (037)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Brown', hex: '#DE9408' },
  { name: 'Plague Brown (039)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Yellow', hex: '#CC9B34' },
  { name: 'Cobra Leather (040)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Brown', hex: '#7B5D2A' },
  { name: 'Dwarf Skin (041)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Flesh', hex: '#CC7C67' },
  { name: 'Parasite Brown (042)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Brown', hex: '#B1481F' },
  { name: 'Beasty Brown (043)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Brown', hex: '#55432D' },
  { name: 'Dark Fleshtone (044)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Flesh', hex: '#4F2B26' },
  { name: 'Charred Brown (045)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Brown', hex: '#39343B' },
  { name: 'Ghost Grey (046)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Grey', hex: '#C3C6CD' },
  { name: 'Wolf Grey (047)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Blue', hex: '#90A2BC' },
  { name: 'Sombre Grey (048)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Blue', hex: '#4C5C7D' },
  { name: 'Stonewall Grey (049)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Grey', hex: '#B5B5B5' },
  { name: 'Cold Grey (050)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Grey', hex: '#999999' },
  { name: 'Black (051)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Black', hex: '#000000' },
  { name: 'Silver (052)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Metallic', hex: '#B5B5BD' },
  { name: 'Chainmail (053)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Metallic', hex: '#7B737B' },
  { name: 'Gunmetal (054)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Metallic', hex: '#393939' },
  { name: 'Polished Gold (055)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Metallic', hex: '#CCCC33' },
  { name: 'Glorious Gold (056)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Metallic', hex: '#E7BD42' },
  { name: 'Bright Bronze (057)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Metallic', hex: '#9C5221' },
  { name: 'Brassy Brass (058)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Metallic', hex: '#735A21' },
  { name: 'Hammered Copper (059)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Metallic', hex: '#73372D' },
  { name: 'Tinny Tin (060)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Metallic', hex: '#393121' },
  { name: 'Khaki (061)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Brown', hex: '#8C806D' },
  { name: 'Earth (062)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Brown', hex: '#655138' },
  { name: 'Desert Yellow (063)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Yellow', hex: '#9C8855' },
  { name: 'Tan (066)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Flesh', hex: '#9F4746' },
  { name: 'Cayman Green (067)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Green', hex: '#285648' },
  { name: 'Imperial Blue (020)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Blue', hex: '#08085A' },
  { name: 'Ultra Marine Blue (022)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Blue', hex: '#29397B' },
  { name: 'Magic Blue (021)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Blue', hex: '#024381' },
  { name: 'Electric Blue (023)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Blue', hex: '#008CBF' },
  { name: 'Falcon Turquoise (024)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Teal', hex: '#006B5A' },
  { name: 'Foul Green (025)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Green', hex: '#239378' },
  { name: 'Jade Green (026)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Green', hex: '#069B7D' },
  { name: 'Scurvy Green (027)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Green', hex: '#026B67' },
  { name: 'Terracotta (065)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Brown', hex: '#6B1306' },
  { name: 'Sick Blue (017)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Purple', hex: '#412A7A' },
  { name: 'Night Blue (019)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Blue', hex: '#000031' },
  { name: 'Stormy Blue (018)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Blue', hex: '#27357E' },
  { name: 'Ice Blue (095)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Blue', hex: '#6B9CCE' },
  { name: 'Bone White (068)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Bone', hex: '#E8BE86' },
  { name: 'Heavy Red (141)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Red', hex: '#991115' },
  { name: 'Heavy Orange (152)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Orange', hex: '#EE3823' },
  { name: 'Heavy Violet (142)', brand: 'Vallejo', range: 'Game Color', colorFamily: 'Purple', hex: '#4F566C' },

  // ──────────────────────────────────────────────
  // Vallejo Model Color (selected)
  // ──────────────────────────────────────────────
  { name: 'White (951)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'White', hex: '#FFFFFF' },
  { name: 'Black (950)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Black', hex: '#000000' },
  { name: 'Flat Red (926)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Red', hex: '#AA3037' },
  { name: 'Vermillion (909)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Red', hex: '#C21920' },
  { name: 'Scarlet (817)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Red', hex: '#DA3630' },
  { name: 'Carmine Red (908)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Red', hex: '#6A0002' },
  { name: 'Flat Yellow (953)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Yellow', hex: '#FFE700' },
  { name: 'Golden Yellow (948)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Yellow', hex: '#FFCE00' },
  { name: 'Lemon Yellow (952)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Yellow', hex: '#FEF10E' },
  { name: 'Light Orange (911)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Orange', hex: '#F68627' },
  { name: 'Bright Orange (851)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Orange', hex: '#F26833' },
  { name: 'Deep Green (970)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Green', hex: '#005221' },
  { name: 'Intermediate Green (891)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Green', hex: '#106B21' },
  { name: 'Park Green Flat (969)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Green', hex: '#008C5D' },
  { name: 'Olive Green (967)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Green', hex: '#A5A542' },
  { name: 'Black Green (980)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Green', hex: '#384E49' },
  { name: 'Dark Prussian Blue (965)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Blue', hex: '#2D567C' },
  { name: 'Blue (925)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Blue', hex: '#27357E' },
  { name: 'Ultramarine (839)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Blue', hex: '#29397B' },
  { name: 'Dark Blue (930)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Blue', hex: '#31639C' },
  { name: 'Sky Blue (961)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Blue', hex: '#8BB9DD' },
  { name: 'Deep Sky Blue (844)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Blue', hex: '#00A6DA' },
  { name: 'Royal Purple (810)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Purple', hex: '#4B2967' },
  { name: 'Violet (960)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Purple', hex: '#4F566C' },
  { name: 'Buff (976)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Bone', hex: '#EFD9A8' },
  { name: 'Ivory (918)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Bone', hex: '#F0F1CE' },
  { name: 'Flat Flesh (955)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Flesh', hex: '#D8A977' },
  { name: 'Light Flesh (928)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Flesh', hex: '#EEC8C7' },
  { name: 'Dark Flesh (927)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Flesh', hex: '#F7944A' },
  { name: 'Flat Brown (984)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Brown', hex: '#663300' },
  { name: 'Flat Earth (983)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Brown', hex: '#87643C' },
  { name: 'Burnt Umber (941)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Brown', hex: '#390008' },
  { name: 'German Grey (995)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Grey', hex: '#4D4A4A' },
  { name: 'Basalt Grey (869)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Grey', hex: '#999999' },
  { name: 'Pale Grey Blue (907)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Grey', hex: '#B5B5B5' },
  { name: 'Silver (997)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Metallic', hex: '#B5B5BD' },
  { name: 'Gold (996)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Metallic', hex: '#E7BD42' },
  { name: 'Bronze (998)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Metallic', hex: '#9C5221' },
  { name: 'Copper (999)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Metallic', hex: '#73372D' },
  { name: 'Gunmetal Grey (863)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Metallic', hex: '#393939' },
  { name: 'Natural Steel (864)', brand: 'Vallejo', range: 'Model Color', colorFamily: 'Metallic', hex: '#7B737B' },

  // ──────────────────────────────────────────────
  // Army Painter — Warpaints
  // ──────────────────────────────────────────────
  { name: 'Matt White', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'White', hex: '#FFFFFF' },
  { name: 'Matt Black', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Black', hex: '#231F20' },
  { name: 'Pure Red', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Red', hex: '#CF2127' },
  { name: 'Dragon Red', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Red', hex: '#9A1B1E' },
  { name: 'Chaotic Red', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Red', hex: '#6C1E10' },
  { name: 'Mars Red', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Red', hex: '#B73B37' },
  { name: 'Vampire Red', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Red', hex: '#981D34' },
  { name: 'Daemonic Yellow', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Yellow', hex: '#FADA06' },
  { name: 'Phoenix Flames', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Orange', hex: '#FAA61A' },
  { name: 'Mythical Orange', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Orange', hex: '#E73D24' },
  { name: 'Fire Lizard', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Orange', hex: '#D67128' },
  { name: 'Deep Blue', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Blue', hex: '#083251' },
  { name: 'Ultramarine Blue', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Blue', hex: '#0F4E85' },
  { name: 'Crystal Blue', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Blue', hex: '#0083C2' },
  { name: 'Electric Blue', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Blue', hex: '#008CBF' },
  { name: 'Viking Blue', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Blue', hex: '#00609A' },
  { name: 'Wolf Grey', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Blue', hex: '#5B8093' },
  { name: 'Voidshield Blue', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Blue', hex: '#2CA2D9' },
  { name: 'Hydra Turquoise', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Teal', hex: '#199BA3' },
  { name: 'Angel Green', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Green', hex: '#0C391D' },
  { name: 'Goblin Green', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Green', hex: '#348941' },
  { name: 'Greenskin', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Green', hex: '#136232' },
  { name: 'Army Green', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Green', hex: '#6E7645' },
  { name: 'Jungle Green', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Green', hex: '#88AC2E' },
  { name: 'Alien Purple', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Purple', hex: '#50317B' },
  { name: 'Oozing Purple', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Purple', hex: '#AA94B4' },
  { name: 'Skeleton Bone', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Bone', hex: '#D3C89D' },
  { name: 'Necrotic Flesh', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Bone', hex: '#BFC292' },
  { name: 'Barbarian Flesh', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Flesh', hex: '#E89C6C' },
  { name: 'Tanned Flesh', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Flesh', hex: '#BC745E' },
  { name: 'Kobold Skin', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Flesh', hex: '#C9A484' },
  { name: 'Leather Brown', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Brown', hex: '#764823' },
  { name: 'Monster Brown', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Brown', hex: '#855C2A' },
  { name: 'Oak Brown', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Brown', hex: '#2B2A24' },
  { name: 'Uniform Grey', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Grey', hex: '#5E6A73' },
  { name: 'Ash Grey', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Grey', hex: '#A2A5A4' },
  { name: 'Dungeon Grey', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Grey', hex: '#686C71' },
  { name: 'Plate Mail Metal', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Metallic', hex: '#7B737B' },
  { name: 'Shining Silver', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Metallic', hex: '#B5B5BD' },
  { name: 'Greedy Gold', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Metallic', hex: '#CCCC33' },
  { name: 'Bright Gold', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Metallic', hex: '#E7BD42' },
  { name: 'Weapon Bronze', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Metallic', hex: '#9C5221' },
  { name: 'Dark Tone Ink', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Black', hex: '#000000' },
  { name: 'Strong Tone Ink', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Brown', hex: '#393121' },
  { name: 'Soft Tone Ink', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Brown', hex: '#843910' },
  { name: 'Blue Tone Ink', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Blue', hex: '#273E51' },
  { name: 'Green Tone Ink', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Green', hex: '#547757' },
  { name: 'Red Tone Ink', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Red', hex: '#630808' },
  { name: 'Purple Tone Ink', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Purple', hex: '#842994' },
  { name: 'Flesh Wash', brand: 'Army Painter', range: 'Warpaints', colorFamily: 'Flesh', hex: '#CE8C42' },

  // ──────────────────────────────────────────────
  // Tamiya — Acrylic Mini (XF flat / X gloss)
  // ──────────────────────────────────────────────
  { name: 'XF-1 Flat Black', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Black', hex: '#1A1A17' },
  { name: 'XF-2 Flat White', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'White', hex: '#F3F1EA' },
  { name: 'XF-3 Flat Yellow', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Yellow', hex: '#F7D917' },
  { name: 'XF-4 Yellow Green', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Green', hex: '#9BA542' },
  { name: 'XF-5 Flat Green', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Green', hex: '#4A7A3D' },
  { name: 'XF-7 Flat Red', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Red', hex: '#B22222' },
  { name: 'XF-8 Flat Blue', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Blue', hex: '#30476E' },
  { name: 'XF-9 Hull Red', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Red', hex: '#522724' },
  { name: 'XF-10 Flat Brown', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Brown', hex: '#6B4423' },
  { name: 'XF-11 J.N. Green', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Green', hex: '#3F5A36' },
  { name: 'XF-12 J.N. Grey', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Grey', hex: '#7B7B73' },
  { name: 'XF-14 J.A. Grey', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Grey', hex: '#7C857B' },
  { name: 'XF-15 Flat Flesh', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Flesh', hex: '#DAA77B' },
  { name: 'XF-16 Flat Aluminum', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Metallic', hex: '#ABABAB' },
  { name: 'XF-17 Sea Blue', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Blue', hex: '#3B5573' },
  { name: 'XF-18 Medium Blue', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Blue', hex: '#4976A5' },
  { name: 'XF-19 Sky Grey', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Grey', hex: '#A5A7A3' },
  { name: 'XF-20 Medium Grey', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Grey', hex: '#858585' },
  { name: 'XF-49 Khaki', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Brown', hex: '#998B6E' },
  { name: 'XF-50 Field Blue', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Blue', hex: '#436872' },
  { name: 'XF-51 Khaki Drab', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Brown', hex: '#857A5E' },
  { name: 'XF-52 Flat Earth', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Brown', hex: '#8B6E4F' },
  { name: 'XF-53 Neutral Grey', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Grey', hex: '#6D6D67' },
  { name: 'XF-54 Dark Sea Grey', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Grey', hex: '#7B8585' },
  { name: 'XF-55 Deck Tan', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Brown', hex: '#C5AF85' },
  { name: 'XF-57 Buff', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Bone', hex: '#CEB678' },
  { name: 'XF-58 Olive Green', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Green', hex: '#5C6E46' },
  { name: 'XF-59 Desert Yellow', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Yellow', hex: '#DAC07C' },
  { name: 'XF-60 Dark Yellow', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Yellow', hex: '#BF9C42' },
  { name: 'XF-62 Olive Drab', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Green', hex: '#4B4E3A' },
  { name: 'XF-63 German Grey', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Grey', hex: '#474845' },
  { name: 'XF-64 Red Brown', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Brown', hex: '#7B3B21' },
  { name: 'XF-65 Field Grey', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Grey', hex: '#6B7561' },
  { name: 'XF-69 NATO Black', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Black', hex: '#2A2B28' },
  { name: 'XF-71 Cockpit Green', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Green', hex: '#4A6452' },
  { name: 'X-1 Black (Gloss)', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Black', hex: '#0A0A0A' },
  { name: 'X-2 White (Gloss)', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'White', hex: '#FFFFFF' },
  { name: 'X-7 Red (Gloss)', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Red', hex: '#C81826' },
  { name: 'X-8 Lemon Yellow', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Yellow', hex: '#EFE40D' },
  { name: 'X-11 Chrome Silver', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Metallic', hex: '#C0C0C0' },
  { name: 'X-12 Gold Leaf', brand: 'Tamiya', range: 'Acrylic Mini', colorFamily: 'Metallic', hex: '#BFA13A' },

  // ──────────────────────────────────────────────
  // Scale75 — Scalecolor
  // ──────────────────────────────────────────────
  { name: 'Black Leather', brand: 'Scale75', range: 'Scalecolor', colorFamily: 'Black', hex: '#1A1510' },
  { name: 'White Sands', brand: 'Scale75', range: 'Scalecolor', colorFamily: 'Bone', hex: '#F0F1CE' },
  { name: 'Nacar', brand: 'Scale75', range: 'Scalecolor', colorFamily: 'White', hex: '#E8E5DC' },
  { name: 'Deep Red', brand: 'Scale75', range: 'Scalecolor', colorFamily: 'Red', hex: '#6A0002' },
  { name: 'Antares Red', brand: 'Scale75', range: 'Scalecolor', colorFamily: 'Red', hex: '#C21920' },
  { name: 'Mars Orange', brand: 'Scale75', range: 'Scalecolor', colorFamily: 'Orange', hex: '#D67128' },
  { name: 'Sol Yellow', brand: 'Scale75', range: 'Scalecolor', colorFamily: 'Yellow', hex: '#FFCE00' },
  { name: 'Sahara Yellow', brand: 'Scale75', range: 'Scalecolor', colorFamily: 'Yellow', hex: '#9C8855' },
  { name: 'Irati Green', brand: 'Scale75', range: 'Scalecolor', colorFamily: 'Green', hex: '#106B21' },
  { name: 'Ardennes Green', brand: 'Scale75', range: 'Scalecolor', colorFamily: 'Green', hex: '#434F38' },
  { name: 'Boreal Green', brand: 'Scale75', range: 'Scalecolor', colorFamily: 'Green', hex: '#455440' },
  { name: 'Spring Green', brand: 'Scale75', range: 'Scalecolor', colorFamily: 'Green', hex: '#A5D610' },
  { name: 'Navy Blue', brand: 'Scale75', range: 'Scalecolor', colorFamily: 'Blue', hex: '#2D567C' },
  { name: 'Adriatic Blue', brand: 'Scale75', range: 'Scalecolor', colorFamily: 'Blue', hex: '#006B5A' },
  { name: 'Bering Blue', brand: 'Scale75', range: 'Scalecolor', colorFamily: 'Blue', hex: '#CEDEE7' },
  { name: 'Sky Blue', brand: 'Scale75', range: 'Scalecolor', colorFamily: 'Blue', hex: '#6B9CCE' },
  { name: 'Arctic Blue', brand: 'Scale75', range: 'Scalecolor', colorFamily: 'Grey', hex: '#999999' },
  { name: 'Violet Blue', brand: 'Scale75', range: 'Scalecolor', colorFamily: 'Purple', hex: '#5A005A' },
  { name: 'Fuchsia', brand: 'Scale75', range: 'Scalecolor', colorFamily: 'Pink', hex: '#9C004A' },
  { name: 'Kalahari Orange', brand: 'Scale75', range: 'Scalecolor', colorFamily: 'Flesh', hex: '#8C5144' },
  { name: 'Golden Skin', brand: 'Scale75', range: 'Scalecolor', colorFamily: 'Bone', hex: '#EFD9A8' },
  { name: 'Pale Skin', brand: 'Scale75', range: 'Scalecolor', colorFamily: 'Flesh', hex: '#EEC8C7' },
  { name: 'Arabic Shadow', brand: 'Scale75', range: 'Scalecolor', colorFamily: 'Brown', hex: '#705E48' },
  { name: 'Iroko', brand: 'Scale75', range: 'Scalecolor', colorFamily: 'Brown', hex: '#C68400' },
  { name: 'Gobi Brown', brand: 'Scale75', range: 'Scalecolor', colorFamily: 'Brown', hex: '#655138' },
  { name: 'Thar Brown', brand: 'Scale75', range: 'Scalecolor', colorFamily: 'Brown', hex: '#9E915C' },
  { name: 'Anthartic Grey', brand: 'Scale75', range: 'Scalecolor', colorFamily: 'Grey', hex: '#4D4A4A' },
  { name: 'Petroleum Grey', brand: 'Scale75', range: 'Scalecolor', colorFamily: 'Grey', hex: '#393939' },
  { name: 'Dwarven Gold', brand: 'Scale75', range: 'Scalecolor', colorFamily: 'Metallic', hex: '#CCCC33' },
  { name: 'Elven Gold', brand: 'Scale75', range: 'Scalecolor', colorFamily: 'Metallic', hex: '#E7BD42' },
  { name: 'Necro Gold', brand: 'Scale75', range: 'Scalecolor', colorFamily: 'Metallic', hex: '#393121' },
  { name: 'Viking Gold', brand: 'Scale75', range: 'Scalecolor', colorFamily: 'Metallic', hex: '#735A21' },

  // ──────────────────────────────────────────────
  // Reaper — Master Series
  // ──────────────────────────────────────────────
  { name: 'Pure White (9039)', brand: 'Reaper', range: 'Master Series', colorFamily: 'White', hex: '#FFFFFF' },
  { name: 'Pure Black (9037)', brand: 'Reaper', range: 'Master Series', colorFamily: 'Black', hex: '#000000' },
  { name: 'Clear Red (9094)', brand: 'Reaper', range: 'Master Series', colorFamily: 'Red', hex: '#C21920' },
  { name: 'Deep Red (9002)', brand: 'Reaper', range: 'Master Series', colorFamily: 'Red', hex: '#6A0002' },
  { name: 'Carnage Red (9135)', brand: 'Reaper', range: 'Master Series', colorFamily: 'Red', hex: '#940008' },
  { name: 'Fire Orange (9006)', brand: 'Reaper', range: 'Master Series', colorFamily: 'Orange', hex: '#F46C2E' },
  { name: 'Phoenix Red (9005)', brand: 'Reaper', range: 'Master Series', colorFamily: 'Orange', hex: '#EE3823' },
  { name: 'Sun Yellow (9008)', brand: 'Reaper', range: 'Master Series', colorFamily: 'Yellow', hex: '#FFCE00' },
  { name: 'Clear Yellow (9095)', brand: 'Reaper', range: 'Master Series', colorFamily: 'Yellow', hex: '#FFF700' },
  { name: 'Pine Green (9010)', brand: 'Reaper', range: 'Master Series', colorFamily: 'Green', hex: '#005221' },
  { name: 'Clear Green (9096)', brand: 'Reaper', range: 'Master Series', colorFamily: 'Green', hex: '#106B21' },
  { name: 'Pale Green (9012)', brand: 'Reaper', range: 'Master Series', colorFamily: 'Green', hex: '#A5D610' },
  { name: 'Field Green (9167)', brand: 'Reaper', range: 'Master Series', colorFamily: 'Green', hex: '#63B521' },
  { name: 'Brilliant Blue (9116)', brand: 'Reaper', range: 'Master Series', colorFamily: 'Blue', hex: '#08085A' },
  { name: 'Breonne Blue (9055)', brand: 'Reaper', range: 'Master Series', colorFamily: 'Blue', hex: '#2D567C' },
  { name: 'Cyan Blue (9117)', brand: 'Reaper', range: 'Master Series', colorFamily: 'Blue', hex: '#31639C' },
  { name: 'Sky Blue (9018)', brand: 'Reaper', range: 'Master Series', colorFamily: 'Blue', hex: '#8BB9DD' },
  { name: 'Twilight Blue (9020)', brand: 'Reaper', range: 'Master Series', colorFamily: 'Blue', hex: '#4E5067' },
  { name: 'Deep Amethyst (9079)', brand: 'Reaper', range: 'Master Series', colorFamily: 'Purple', hex: '#562F7E' },
  { name: 'Nightshade Purple (9022)', brand: 'Reaper', range: 'Master Series', colorFamily: 'Purple', hex: '#4F566C' },
  { name: 'Clear Plum (9132)', brand: 'Reaper', range: 'Master Series', colorFamily: 'Purple', hex: '#5A005A' },
  { name: 'Rosy Highlight (9069)', brand: 'Reaper', range: 'Master Series', colorFamily: 'Flesh', hex: '#EEC8C7' },
  { name: 'Rosy Skin (9068)', brand: 'Reaper', range: 'Master Series', colorFamily: 'Flesh', hex: '#F78C5A' },
  { name: 'Tanned Leather (9031)', brand: 'Reaper', range: 'Master Series', colorFamily: 'Brown', hex: '#DE9408' },
  { name: 'Intense Brown (9138)', brand: 'Reaper', range: 'Master Series', colorFamily: 'Brown', hex: '#663300' },
  { name: 'Muddy Brown (9028)', brand: 'Reaper', range: 'Master Series', colorFamily: 'Brown', hex: '#390008' },
  { name: 'Yellowed Bone (9143)', brand: 'Reaper', range: 'Master Series', colorFamily: 'Bone', hex: '#EFD9A8' },
  { name: 'Weathered Stone (9087)', brand: 'Reaper', range: 'Master Series', colorFamily: 'Grey', hex: '#B5B5B5' },
  { name: 'Rainy Grey (9038)', brand: 'Reaper', range: 'Master Series', colorFamily: 'Grey', hex: '#999999' },
  { name: 'Polished Silver (9054)', brand: 'Reaper', range: 'Master Series', colorFamily: 'Metallic', hex: '#B5B5BD' },
  { name: 'Honed Steel (9053)', brand: 'Reaper', range: 'Master Series', colorFamily: 'Metallic', hex: '#7B737B' },
  { name: 'Shadowed Steel (9052)', brand: 'Reaper', range: 'Master Series', colorFamily: 'Metallic', hex: '#393939' },
  { name: 'Antique Gold (9050)', brand: 'Reaper', range: 'Master Series', colorFamily: 'Metallic', hex: '#E7BD42' },
  { name: 'New Gold (9051)', brand: 'Reaper', range: 'Master Series', colorFamily: 'Metallic', hex: '#CCCC33' },
  { name: 'Ancient Bronze (9049)', brand: 'Reaper', range: 'Master Series', colorFamily: 'Metallic', hex: '#9C5221' },

  // ──────────────────────────────────────────────
  // Privateer Press — P3 Formula
  // ──────────────────────────────────────────────
  { name: 'Morrow White', brand: 'P3', range: 'Formula P3', colorFamily: 'White', hex: '#FEFBFD' },
  { name: 'Thamar Black', brand: 'P3', range: 'Formula P3', colorFamily: 'Black', hex: '#040707' },
  { name: 'Khador Red Base', brand: 'P3', range: 'Formula P3', colorFamily: 'Red', hex: '#EE2824' },
  { name: 'Skorne Red', brand: 'P3', range: 'Formula P3', colorFamily: 'Red', hex: '#B01F24' },
  { name: 'Sanguine Base', brand: 'P3', range: 'Formula P3', colorFamily: 'Red', hex: '#6C160F' },
  { name: 'Khardic Flesh', brand: 'P3', range: 'Formula P3', colorFamily: 'Flesh', hex: '#CB7B5B' },
  { name: 'Heartfire', brand: 'P3', range: 'Formula P3', colorFamily: 'Orange', hex: '#F6B046' },
  { name: 'Sulfuric Yellow', brand: 'P3', range: 'Formula P3', colorFamily: 'Yellow', hex: '#F0D233' },
  { name: 'Cygnus Yellow', brand: 'P3', range: 'Formula P3', colorFamily: 'Yellow', hex: '#F3E72E' },
  { name: 'Iosan Green', brand: 'P3', range: 'Formula P3', colorFamily: 'Green', hex: '#22A854' },
  { name: 'Gnarls Green', brand: 'P3', range: 'Formula P3', colorFamily: 'Green', hex: '#126232' },
  { name: 'Wurm Green', brand: 'P3', range: 'Formula P3', colorFamily: 'Green', hex: '#8FBE40' },
  { name: 'Ordic Olive', brand: 'P3', range: 'Formula P3', colorFamily: 'Green', hex: '#6E7E36' },
  { name: 'Exile Blue', brand: 'P3', range: 'Formula P3', colorFamily: 'Blue', hex: '#203367' },
  { name: 'Cygnar Base Blue', brand: 'P3', range: 'Formula P3', colorFamily: 'Blue', hex: '#124B9B' },
  { name: 'Cygnar Blue Highlight', brand: 'P3', range: 'Formula P3', colorFamily: 'Blue', hex: '#1F75BB' },
  { name: 'Trollblood Base', brand: 'P3', range: 'Formula P3', colorFamily: 'Blue', hex: '#13899B' },
  { name: 'Meredius Blue', brand: 'P3', range: 'Formula P3', colorFamily: 'Blue', hex: '#00B0B9' },
  { name: 'Beaten Purple', brand: 'P3', range: 'Formula P3', colorFamily: 'Purple', hex: '#552A72' },
  { name: 'Murderous Magenta', brand: 'P3', range: 'Formula P3', colorFamily: 'Pink', hex: '#A81F5E' },
  { name: 'Moldy Ochre', brand: 'P3', range: 'Formula P3', colorFamily: 'Yellow', hex: '#DDB43E' },
  { name: 'Rucksack Tan', brand: 'P3', range: 'Formula P3', colorFamily: 'Brown', hex: '#B4973F' },
  { name: 'Bootstrap Leather', brand: 'P3', range: 'Formula P3', colorFamily: 'Brown', hex: '#956939' },
  { name: 'Gun Corps Brown', brand: 'P3', range: 'Formula P3', colorFamily: 'Brown', hex: '#937D48' },
  { name: 'Umbral Umber', brand: 'P3', range: 'Formula P3', colorFamily: 'Brown', hex: '#390008' },
  { name: 'Menoth White Base', brand: 'P3', range: 'Formula P3', colorFamily: 'Bone', hex: '#EFD9A8' },
  { name: 'Menoth White Highlight', brand: 'P3', range: 'Formula P3', colorFamily: 'Bone', hex: '#F0F1CE' },
  { name: 'Jack Bone', brand: 'P3', range: 'Formula P3', colorFamily: 'Bone', hex: '#D6D4AA' },
  { name: 'Midlund Flesh', brand: 'P3', range: 'Formula P3', colorFamily: 'Flesh', hex: '#F0A983' },
  { name: 'Ryn Flesh', brand: 'P3', range: 'Formula P3', colorFamily: 'Flesh', hex: '#EEC8C7' },
  { name: 'Bastion Grey', brand: 'P3', range: 'Formula P3', colorFamily: 'Grey', hex: '#777965' },
  { name: 'Greatcoat Grey', brand: 'P3', range: 'Formula P3', colorFamily: 'Grey', hex: '#4D5861' },
  { name: 'Ironhull Grey', brand: 'P3', range: 'Formula P3', colorFamily: 'Grey', hex: '#8E969B' },
  { name: 'Pig Iron', brand: 'P3', range: 'Formula P3', colorFamily: 'Metallic', hex: '#393939' },
  { name: 'Cold Steel', brand: 'P3', range: 'Formula P3', colorFamily: 'Metallic', hex: '#7B737B' },
  { name: 'Quicksilver', brand: 'P3', range: 'Formula P3', colorFamily: 'Metallic', hex: '#B5B5BD' },
  { name: 'Brass Balls', brand: 'P3', range: 'Formula P3', colorFamily: 'Metallic', hex: '#E7BD42' },
  { name: 'Molten Bronze', brand: 'P3', range: 'Formula P3', colorFamily: 'Metallic', hex: '#9C5221' },
  { name: 'Solid Gold', brand: 'P3', range: 'Formula P3', colorFamily: 'Metallic', hex: '#CCCC33' },
];
